shared_props = {
    'visible': [
        'hidden',
        'visible',
        'initial',
        'inherit',
    ]
}
props = {
    'azimuth': {'dropdown': True, 'props': []},
    'backface-visibility': {'dropdown': True, 'props': shared_props['visible']},
    'background': {'dropdown': True, 'props': []},
    'background-attachment': {'dropdown': True, 'props': []},
    'background-color': {'dropdown': True, 'props': []},
    'background-image': {'dropdown': True, 'props': []},
    'background-position': {'dropdown': True, 'props': []},
    'background-position-x': {'dropdown': True, 'props': []},
    'background-position-y': {'dropdown': True, 'props': []},
    'background-repeat': {'dropdown': True, 'props': [
        'no-repeat',
        'repeat-x',
        'repeat-y',
        'repeat'
    ]},
    'behavior': {'dropdown': True, 'props': []},
    'border': {'dropdown': True, 'props': [
        'none', 'hidden', 'dotted', 'dashed', 'solid', 'double',
        'groove', 'ridge', 'inset', 'outset', 'initial', 'inherit'
    ]},
    'border-bottom': {'dropdown': True, 'props': []},
    'border-bottom-color': {'dropdown': True, 'props': []},
    'border-bottom-style': {'dropdown': True, 'props': []},
    'border-bottom-width': {'dropdown': True, 'props': []},
    'border-collapse': {'dropdown': True, 'props': []},
    'border-color': {'dropdown': True, 'props': []},
    'border-left': {'dropdown': True, 'props': []},
    'border-left-color': {'dropdown': True, 'props': []},
    'border-left-style': {'dropdown': True, 'props': []},
    'border-left-width': {'dropdown': True, 'props': []},
    'border-right': {'dropdown': True, 'props': []},
    'border-right-color': {'dropdown': True, 'props': []},
    'border-right-style': {'dropdown': True, 'props': []},
    'border-right-width': {'dropdown': True, 'props': []},
    'border-spacing': {'dropdown': True, 'props': []},
    'border-style': {'dropdown': True, 'props': []},
    'border-top': {'dropdown': True, 'props': []},
    'border-top-color': {'dropdown': True, 'props': []},
    'border-top-style': {'dropdown': True, 'props': []},
    'border-top-width': {'dropdown': True, 'props': []},
    'border-width': {'dropdown': True, 'props': []},
    'bottom': {'dropdown': True, 'props': []},
    'box-shadow': {'dropdown': True, 'props': []},
    'caption-side': {'dropdown': True, 'props': []},
    'clear': {'dropdown': True, 'props': [
        'both',
        'inherit',
        'left',
        'right'
    ]},
    'clip': {'dropdown': True, 'props': []},
    'color': {'dropdown': True, 'props': []},
    'content': {'dropdown': True, 'props': []},
    'counter-increment': {'dropdown': True, 'props': []},
    'counter-reset': {'dropdown': True, 'props': []},
    'cue': {'dropdown': True, 'props': []},
    'cue-after': {'dropdown': True, 'props': []},
    'cue-before': {'dropdown': True, 'props': []},
    'cursor': {'dropdown': True, 'props': []},
    'direction': {'dropdown': True, 'props': []},
    'display': {'dropdown': True, 'props': []},
    'elevation': {'dropdown': True, 'props': []},
    'empty-cells': {'dropdown': True, 'props': []},
    'filter': {'dropdown': True, 'props': []},
    'float': {'dropdown': True, 'props': []},
    'font': {'dropdown': True, 'props': []},
    'font-family': {'dropdown': True, 'props': []},
    'font-size': {'dropdown': True, 'props': []},
    'font-size-adjust': {'dropdown': True, 'props': []},
    'font-stretch': {'dropdown': True, 'props': []},
    'font-style': {'dropdown': True, 'props': []},
    'font-variant': {'dropdown': True, 'props': []},
    'font-weight': {'dropdown': True, 'props': []},
    'height': {'dropdown': False, 'props': []},
    'ime-mode': {'dropdown': True, 'props': []},
    'include-source': {'dropdown': True, 'props': []},
    'layer-background-color': {'dropdown': True, 'props': []},
    'layer-background-image': {'dropdown': True, 'props': []},
    'layout-flow': {'dropdown': True, 'props': []},
    'layout-grid': {'dropdown': True, 'props': []},
    'layout-grid-char': {'dropdown': True, 'props': []},
    'layout-grid-char-spacing': {'dropdown': True, 'props': []},
    'layout-grid-line': {'dropdown': True, 'props': []},
    'layout-grid-mode': {'dropdown': True, 'props': []},
    'layout-grid-type': {'dropdown': True, 'props': []},
    'left': {'dropdown': True, 'props': []},
    'letter-spacing': {'dropdown': True, 'props': []},
    'line-break': {'dropdown': True, 'props': []},
    'line-height': {'dropdown': True, 'props': []},
    'list-style': {'dropdown': True, 'props': []},
    'list-style-image': {'dropdown': True, 'props': []},
    'list-style-position': {'dropdown': True, 'props': []},
    'list-style-type': {'dropdown': True, 'props': []},
    'margin': {'dropdown': True, 'props': []},
    'margin-bottom': {'dropdown': True, 'props': []},
    'margin-left': {'dropdown': True, 'props': []},
    'margin-right': {'dropdown': True, 'props': []},
    'margin-top': {'dropdown': True, 'props': []},
    'marker-offset': {'dropdown': True, 'props': []},
    'marks': {'dropdown': True, 'props': []},
    'max-height': {'dropdown': True, 'props': []},
    'max-width': {'dropdown': True, 'props': []},
    'min-height': {'dropdown': True, 'props': []},
    'min-width': {'dropdown': True, 'props': []},
    '-moz-binding': {'dropdown': True, 'props': []},
    '-moz-border-radius': {'dropdown': True, 'props': []},
    '-moz-border-radius-topleft': {'dropdown': True, 'props': []},
    '-moz-border-radius-topright': {'dropdown': True, 'props': []},
    '-moz-border-radius-bottomright': {'dropdown': True, 'props': []},
    '-moz-border-radius-bottomleft': {'dropdown': True, 'props': []},
    '-moz-border-top-colors': {'dropdown': True, 'props': []},
    '-moz-border-right-colors': {'dropdown': True, 'props': []},
    '-moz-border-bottom-colors': {'dropdown': True, 'props': []},
    '-moz-border-left-colors': {'dropdown': True, 'props': []},
    '-moz-opacity': {'dropdown': True, 'props': []},
    '-moz-outline': {'dropdown': True, 'props': []},
    '-moz-outline-color': {'dropdown': True, 'props': []},
    '-moz-outline-style': {'dropdown': True, 'props': []},
    '-moz-outline-width': {'dropdown': True, 'props': []},
    '-moz-user-focus': {'dropdown': True, 'props': []},
    '-moz-user-input': {'dropdown': True, 'props': []},
    '-moz-user-modify': {'dropdown': True, 'props': []},
    '-moz-user-select': {'dropdown': True, 'props': []},
    'orphans': {'dropdown': True, 'props': []},
    'outline': {'dropdown': True, 'props': []},
    'outline-color': {'dropdown': True, 'props': []},
    'outline-style': {'dropdown': True, 'props': []},
    'outline-width': {'dropdown': True, 'props': []},
    'overflow': {'dropdown': True, 'props': []},
    'overflow-X': {'dropdown': True, 'props': []},
    'overflow-Y': {'dropdown': True, 'props': []},
    'padding': {'dropdown': True, 'props': []},
    'padding-bottom': {'dropdown': True, 'props': []},
    'padding-left': {'dropdown': True, 'props': []},
    'padding-right': {'dropdown': True, 'props': []},
    'padding-top': {'dropdown': True, 'props': []},
    'page': {'dropdown': True, 'props': []},
    'page-break-after': {'dropdown': True, 'props': []},
    'page-break-before': {'dropdown': True, 'props': []},
    'page-break-inside': {'dropdown': True, 'props': []},
    'pause': {'dropdown': True, 'props': []},
    'pause-after': {'dropdown': True, 'props': []},
    'pause-before': {'dropdown': True, 'props': []},
    'pitch': {'dropdown': True, 'props': []},
    'pitch-range': {'dropdown': True, 'props': []},
    'play-during': {'dropdown': True, 'props': []},
    'position': {'dropdown': True, 'props': []},
    'quotes': {'dropdown': True, 'props': []},
    '-replace': {'dropdown': True, 'props': []},
    'richness': {'dropdown': True, 'props': []},
    'right': {'dropdown': True, 'props': []},
    'ruby-align': {'dropdown': True, 'props': []},
    'ruby-overhang': {'dropdown': True, 'props': []},
    'ruby-position': {'dropdown': True, 'props': []},
    '-set-link-source': {'dropdown': True, 'props': []},
    'size': {'dropdown': True, 'props': []},
    'speak': {'dropdown': True, 'props': []},
    'speak-header': {'dropdown': True, 'props': []},
    'speak-numeral': {'dropdown': True, 'props': []},
    'speak-punctuation': {'dropdown': True, 'props': []},
    'speech-rate': {'dropdown': True, 'props': []},
    'stress': {'dropdown': True, 'props': []},
    'scrollbar-arrow-color': {'dropdown': True, 'props': []},
    'scrollbar-base-color': {'dropdown': True, 'props': []},
    'scrollbar-dark-shadow-color': {'dropdown': True, 'props': []},
    'scrollbar-face-color': {'dropdown': True, 'props': []},
    'scrollbar-highlight-color': {'dropdown': True, 'props': []},
    'scrollbar-shadow-color': {'dropdown': True, 'props': []},
    'scrollbar-3d-light-color': {'dropdown': True, 'props': []},
    'scrollbar-track-color': {'dropdown': True, 'props': []},
    'table-layout': {'dropdown': True, 'props': []},
    'text-align': {'dropdown': True, 'props': []},
    'text-align-last': {'dropdown': True, 'props': []},
    'text-decoration': {'dropdown': True, 'props': []},
    'text-indent': {'dropdown': True, 'props': []},
    'text-justify': {'dropdown': True, 'props': []},
    'text-overflow': {'dropdown': True, 'props': []},
    'text-shadow': {'dropdown': True, 'props': []},
    'text-transform': {'dropdown': True, 'props': []},
    'text-autospace': {'dropdown': True, 'props': []},
    'text-kashida-space': {'dropdown': True, 'props': []},
    'text-underline-position': {'dropdown': True, 'props': []},
    'top': {'dropdown': True, 'props': []},
    'unicode-bidi': {'dropdown': True, 'props': []},
    '-use-link-source': {'dropdown': True, 'props': []},
    'vertical-align': {'dropdown': True, 'props': []},
    'visibility': {'dropdown': True, 'props': shared_props['visible']},
    'voice-family': {'dropdown': True, 'props': []},
    'volume': {'dropdown': True, 'props': []},
    'white-space': {'dropdown': True, 'props': []},
    'widows': {'dropdown': True, 'props': []},
    'width': {'dropdown': False, 'props': []},
    'word-break': {'dropdown': True, 'props': []},
    'word-spacing': {'dropdown': True, 'props': []},
    'word-wrap': {'dropdown': True, 'props': []},
    'writing-mode': {'dropdown': True, 'props': []},
    'z-index': {'dropdown': True, 'props': []},
    'zoom': {'dropdown': True, 'props': []},
}
